# Generated by Django 5.1.3 on 2024-11-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0007_alter_job_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_date']},
        ),
    ]
