# Generated by Django 5.1.3 on 2024-11-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_applicant_alter_application_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-submitted_date']},
        ),
        migrations.AlterField(
            model_name='application',
            name='interview',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
